name: stm8flash CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get -y install libusb-1.0-0-dev pkg-config
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: make
      run: make
